/*
 @licstart  The following is the entire license notice for the JavaScript code in this file.

 The MIT License (MIT)

 Copyright (C) 1997-2020 by Dimitri van Heesch

 Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 and associated documentation files (the "Software"), to deal in the Software without restriction,
 including without limitation the rights to use, copy, modify, merge, publish, distribute,
 sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all copies or
 substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
 BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

 @licend  The above is the entire license notice for the JavaScript code in this file
*/
var NAVTREE =
[
  [ "KAT - Advanced Medical", "index.html", [
    [ "fnc_checkAirway", "d4/dd5/md_addons_airway_functions_fnc_check_airway.html", null ],
    [ "fnc_checkRecovery", "de/d29/md_addons_airway_functions_fnc_check_recovery.html", null ],
    [ "fnc_displayPatientInformation", "df/d7c/md_addons_airway_functions_fnc_display_patient_information.html", null ],
    [ "fnc_handleAirway", "d2/df1/md_addons_airway_functions_fnc_handle_airway.html", null ],
    [ "fnc_handlePuking", "d3/df7/md_addons_airway_functions_fnc_handle_puking.html", null ],
    [ "fnc_init", "d7/dee/md_addons_airway_functions_fnc_init.html", null ],
    [ "fnc_setUnconscious", "d5/dc0/md_addons_airway_functions_fnc_set_unconscious.html", null ],
    [ "fnc_treatmentAdvanced_Accuvac", "d2/d58/md_addons_airway_functions_fnc_treatment_advanced__accuvac.html", null ],
    [ "fnc_treatmentAdvanced_AccuvacLocal", "d1/db2/md_addons_airway_functions_fnc_treatment_advanced__accuvac_local.html", null ],
    [ "fnc_treatmentAdvanced_airway", "de/db3/md_addons_airway_functions_fnc_treatment_advanced_airway.html", null ],
    [ "fnc_treatmentAdvanced_airwayLocal", "d2/dd6/md_addons_airway_functions_fnc_treatment_advanced_airway_local.html", null ],
    [ "fnc_treatmentAdvanced_CancelRecoveryPosition", "d9/dd5/md_addons_airway_functions_fnc_treatment_advanced__cancel_recovery_position.html", null ],
    [ "fnc_treatmentAdvanced_CancelRecoveryPositionLocal", "d0/db1/md_addons_airway_functions_fnc_treatment_advanced__cancel_recovery_position_local.html", null ],
    [ "fnc_treatmentAdvanced_overstretchHead", "d9/d09/md_addons_airway_functions_fnc_treatment_advanced_overstretch_head.html", null ],
    [ "fnc_treatmentAdvanced_RecoveryPosition", "dc/d1b/md_addons_airway_functions_fnc_treatment_advanced__recovery_position.html", null ],
    [ "fnc_treatmentAdvanced_RecoveryPositionLocal", "d4/def/md_addons_airway_functions_fnc_treatment_advanced__recovery_position_local.html", null ],
    [ "fnc_treatmentAdvanced_RemoveAirwayItem", "d4/d5e/md_addons_airway_functions_fnc_treatment_advanced__remove_airway_item.html", null ],
    [ "fnc_treatmentAdvanced_RemoveAirwayItemLocal", "d3/dd5/md_addons_airway_functions_fnc_treatment_advanced__remove_airway_item_local.html", null ],
    [ "fnc_treatmentAdvanced_turnaroundHead", "d8/dcc/md_addons_airway_functions_fnc_treatment_advanced_turnaround_head.html", null ],
    [ "fnc_updateInjuryList", "d3/df7/md_addons_airway_functions_fnc_update_injury_list.html", null ],
    [ "fnc_updateLogList", "dc/d12/md_addons_airway_functions_fnc_update_log_list.html", null ],
    [ "XEH_postInit", "d3/d8f/md_addons_airway__x_e_h_post_init.html", null ],
    [ "XEH_preInit", "d5/d6f/md_addons_airway__x_e_h_pre_init.html", null ],
    [ "fnc_canUseBVM", "d1/daa/md_addons_breathing_functions_fnc_can_use_b_v_m.html", null ],
    [ "fnc_checkPulseOximeter", "dd/d00/md_addons_breathing_functions_fnc_check_pulse_oximeter.html", null ],
    [ "fnc_fullHealLocal", "dd/d94/md_addons_breathing_functions_fnc_full_heal_local.html", null ],
    [ "fnc_handleBreathing", "da/d6c/md_addons_breathing_functions_fnc_handle_breathing.html", null ],
    [ "fnc_handlePulmoHit", "d0/d36/md_addons_breathing_functions_fnc_handle_pulmo_hit.html", null ],
    [ "fnc_hasBVM", "d1/d00/md_addons_breathing_functions_fnc_has_b_v_m.html", null ],
    [ "fnc_hasOxygenTank", "db/d5c/md_addons_breathing_functions_fnc_has_oxygen_tank.html", null ],
    [ "fnc_init", "d2/dba/md_addons_breathing_functions_fnc_init.html", null ],
    [ "fnc_listenLungs", "d7/dd2/md_addons_breathing_functions_fnc_listen_lungs.html", null ],
    [ "fnc_lowSpO2pp", "d7/d86/md_addons_breathing_functions_fnc_low_sp_o2pp.html", null ],
    [ "fnc_refillOxygenTank", "d5/d97/md_addons_breathing_functions_fnc_refill_oxygen_tank.html", null ],
    [ "fnc_treatmentAdvanced_chestSeal", "d1/d6b/md_addons_breathing_functions_fnc_treatment_advanced_chest_seal.html", null ],
    [ "fnc_treatmentAdvanced_chestSealLocal", "d8/d4c/md_addons_breathing_functions_fnc_treatment_advanced_chest_seal_local.html", null ],
    [ "fnc_treatmentAdvanced_Cyanosis", "d4/dd1/md_addons_breathing_functions_fnc_treatment_advanced__cyanosis.html", null ],
    [ "fnc_treatmentAdvanced_CyanosisLocal", "d3/d14/md_addons_breathing_functions_fnc_treatment_advanced__cyanosis_local.html", null ],
    [ "fnc_treatmentAdvanced_hemopneumothorax", "d6/d2d/md_addons_breathing_functions_fnc_treatment_advanced_hemopneumothorax.html", null ],
    [ "fnc_treatmentAdvanced_hemopneumothoraxLocal", "d0/d01/md_addons_breathing_functions_fnc_treatment_advanced_hemopneumothorax_local.html", null ],
    [ "fnc_treatmentAdvanced_pulseoximeter", "d0/d44/md_addons_breathing_functions_fnc_treatment_advanced_pulseoximeter.html", null ],
    [ "fnc_treatmentAdvanced_pulseoximeterLocal", "d0/dc6/md_addons_breathing_functions_fnc_treatment_advanced_pulseoximeter_local.html", null ],
    [ "fnc_treatmentAdvanced_removePulseoximeter", "d4/d89/md_addons_breathing_functions_fnc_treatment_advanced_remove_pulseoximeter.html", null ],
    [ "fnc_treatmentAdvanced_tensionpneumothorax", "da/d7e/md_addons_breathing_functions_fnc_treatment_advanced_tensionpneumothorax.html", null ],
    [ "fnc_treatmentAdvanced_tensionpneumothoraxLocal", "de/df9/md_addons_breathing_functions_fnc_treatment_advanced_tensionpneumothorax_local.html", null ],
    [ "fnc_useBVM", "dc/d2e/md_addons_breathing_functions_fnc_use_b_v_m.html", null ],
    [ "XEH_postInit", "d8/d23/md_addons_breathing__x_e_h_post_init.html", null ],
    [ "XEH_preInit", "d0/dae/md_addons_breathing__x_e_h_pre_init.html", null ],
    [ "fnc_addLoadAction", "dd/d86/md_addons_chemical_functions_fnc_add_load_action.html", null ],
    [ "fnc_afterWait", "df/d9a/md_addons_chemical_functions_fnc_after_wait.html", null ],
    [ "fnc_AttributeRadius", "dd/d52/md_addons_chemical_functions_fnc__attribute_radius.html", null ],
    [ "fnc_breathing", "de/d7e/md_addons_chemical_functions_fnc_breathing.html", null ],
    [ "fnc_canPutGasMask", "d4/d00/md_addons_chemical_functions_fnc_can_put_gas_mask.html", null ],
    [ "fnc_canReplaceFilter", "d0/d5a/md_addons_chemical_functions_fnc_can_replace_filter.html", null ],
    [ "fnc_CASCreateGas", "d8/d1f/md_addons_chemical_functions_fnc__c_a_s_create_gas.html", null ],
    [ "fnc_changeGasMaskFilter", "dd/d80/md_addons_chemical_functions_fnc_change_gas_mask_filter.html", null ],
    [ "fnc_checkGasMaskDur", "df/df8/md_addons_chemical_functions_fnc_check_gas_mask_dur.html", null ],
    [ "fnc_chemDetector", "d1/d3f/md_addons_chemical_functions_fnc_chem_detector.html", null ],
    [ "fnc_coughing", "d0/da5/md_addons_chemical_functions_fnc_coughing.html", null ],
    [ "fnc_createSealAction", "d1/dd8/md_addons_chemical_functions_fnc_create_seal_action.html", null ],
    [ "fnc_createZone", "de/d4b/md_addons_chemical_functions_fnc_create_zone.html", null ],
    [ "fnc_csGrenadeThrownFuze", "de/d43/md_addons_chemical_functions_fnc_cs_grenade_thrown_fuze.html", null ],
    [ "fnc_displayGasMaskDur", "d7/dfe/md_addons_chemical_functions_fnc_display_gas_mask_dur.html", null ],
    [ "fnc_gasAI", "d6/d62/md_addons_chemical_functions_fnc_gas_a_i.html", null ],
    [ "fnc_gasCheck", "d2/d0a/md_addons_chemical_functions_fnc_gas_check.html", null ],
    [ "fnc_gasCheckLocal", "db/d6a/md_addons_chemical_functions_fnc_gas_check_local.html", null ],
    [ "fnc_gasmodule", "df/d9a/md_addons_chemical_functions_fnc_gasmodule.html", null ],
    [ "fnc_GasTripEffect", "dd/db1/md_addons_chemical_functions_fnc__gas_trip_effect.html", null ],
    [ "fnc_getChemDetectorState", "d1/d6a/md_addons_chemical_functions_fnc_get_chem_detector_state.html", null ],
    [ "fnc_getList", "dd/dbf/md_addons_chemical_functions_fnc_get_list.html", null ],
    [ "fnc_giveUnitGasMask", "d7/d76/md_addons_chemical_functions_fnc_give_unit_gas_mask.html", null ],
    [ "fnc_handleCSGas", "d4/d1c/md_addons_chemical_functions_fnc_handle_c_s_gas.html", null ],
    [ "fnc_handleFired", "dd/d57/md_addons_chemical_functions_fnc_handle_fired.html", null ],
    [ "fnc_handleGasMaskDur", "dc/d6a/md_addons_chemical_functions_fnc_handle_gas_mask_dur.html", null ],
    [ "fnc_handleSlotItemChanged", "d1/d5c/md_addons_chemical_functions_fnc_handle_slot_item_changed.html", null ],
    [ "fnc_hasGasmask", "d5/da3/md_addons_chemical_functions_fnc_has_gasmask.html", null ],
    [ "fnc_hasGasMaskON", "d7/d67/md_addons_chemical_functions_fnc_has_gas_mask_o_n.html", null ],
    [ "fnc_init", "db/d72/md_addons_chemical_functions_fnc_init.html", null ],
    [ "fnc_initModule", "df/d51/md_addons_chemical_functions_fnc_init_module.html", null ],
    [ "fnc_spawnGasSmoke", "d0/d1f/md_addons_chemical_functions_fnc_spawn_gas_smoke.html", null ],
    [ "fnc_spawnSmoke", "d1/d60/md_addons_chemical_functions_fnc_spawn_smoke.html", null ],
    [ "fnc_throwGrenade", "d2/dd1/md_addons_chemical_functions_fnc_throw_grenade.html", null ],
    [ "fnc_ui_gasModule", "d8/d64/md_addons_chemical_functions_fnc_ui_gas_module.html", null ],
    [ "fnc_updateBodyImage", "df/da7/md_addons_chemical_functions_fnc_update_body_image.html", null ],
    [ "XEH_postInit", "d2/d6d/md_addons_chemical__x_e_h_post_init.html", null ],
    [ "XEH_preInit", "d3/d59/md_addons_chemical__x_e_h_pre_init.html", null ],
    [ "fnc_AED_sound", "d5/d00/md_addons_circulation_functions_fnc__a_e_d_sound.html", null ],
    [ "fnc_AEDanalyze", "d4/d68/md_addons_circulation_functions_fnc__a_e_danalyze.html", null ],
    [ "fnc_AEDFailure", "d7/d56/md_addons_circulation_functions_fnc__a_e_d_failure.html", null ],
    [ "fnc_AEDProgress", "d1/d8d/md_addons_circulation_functions_fnc__a_e_d_progress.html", null ],
    [ "fnc_AEDStart", "db/d86/md_addons_circulation_functions_fnc__a_e_d_start.html", null ],
    [ "fnc_AEDStationCondition", "de/de8/md_addons_circulation_functions_fnc__a_e_d_station_condition.html", null ],
    [ "fnc_AEDSuccess", "de/d74/md_addons_circulation_functions_fnc__a_e_d_success.html", null ],
    [ "fnc_AEDXCondition", "d8/d5b/md_addons_circulation_functions_fnc__a_e_d_x_condition.html", null ],
    [ "fnc_attachAEDX", "d4/d87/md_addons_circulation_functions_fnc_attach_a_e_d_x.html", null ],
    [ "fnc_attachAEDXVehicle", "d3/df7/md_addons_circulation_functions_fnc_attach_a_e_d_x_vehicle.html", null ],
    [ "fnc_bloodType", "d1/dbd/md_addons_circulation_functions_fnc_blood_type.html", null ],
    [ "fnc_canCheckDogtag", "db/db8/md_addons_circulation_functions_fnc_can_check_dogtag.html", null ],
    [ "fnc_canDraw", "d9/d5e/md_addons_circulation_functions_fnc_can_draw.html", null ],
    [ "fnc_compatible", "dd/df2/md_addons_circulation_functions_fnc_compatible.html", null ],
    [ "fnc_cprLocal", "d7/d0f/md_addons_circulation_functions_fnc_cpr_local.html", null ],
    [ "fnc_cprSuccess", "d8/d85/md_addons_circulation_functions_fnc_cpr_success.html", null ],
    [ "fnc_drawBlood", "d5/deb/md_addons_circulation_functions_fnc_draw_blood.html", null ],
    [ "fnc_generateBloodType", "d3/d7a/md_addons_circulation_functions_fnc_generate_blood_type.html", null ],
    [ "fnc_getDogtagData", "db/d58/md_addons_circulation_functions_fnc_get_dogtag_data.html", null ],
    [ "fnc_groupID", "de/df0/md_addons_circulation_functions_fnc_group_i_d.html", null ],
    [ "fnc_handleTreatment", "dd/dfe/md_addons_circulation_functions_fnc_handle_treatment.html", null ],
    [ "fnc_init", "d5/d24/md_addons_circulation_functions_fnc_init.html", null ],
    [ "fnc_onCloseDialog", "db/d94/md_addons_circulation_functions_fnc_on_close_dialog.html", null ],
    [ "fnc_placeAED", "d7/d21/md_addons_circulation_functions_fnc_place_a_e_d.html", null ],
    [ "fnc_removeLog", "d8/de4/md_addons_circulation_functions_fnc_remove_log.html", null ],
    [ "fnc_returnAED_X", "da/d22/md_addons_circulation_functions_fnc_return_a_e_d__x.html", null ],
    [ "fnc_treatment", "d8/d1e/md_addons_circulation_functions_fnc_treatment.html", null ],
    [ "fnc_treatmentAdvanced_IV", "db/d10/md_addons_circulation_functions_fnc_treatment_advanced__i_v.html", null ],
    [ "fnc_updateInternalBleeding", "d0/d9a/md_addons_circulation_functions_fnc_update_internal_bleeding.html", null ],
    [ "fnc_vehicleCheck", "d8/d37/md_addons_circulation_functions_fnc_vehicle_check.html", null ],
    [ "fnc_wrongBloodTreatment", "d2/dac/md_addons_circulation_functions_fnc_wrong_blood_treatment.html", null ],
    [ "XEH_postInit", "dc/dc2/md_addons_circulation__x_e_h_post_init.html", null ],
    [ "XEH_preInit", "d3/d3e/md_addons_circulation__x_e_h_pre_init.html", null ],
    [ "fnc_onMenuOpen", "da/de8/md_addons_gui_functions_fnc_on_menu_open.html", null ],
    [ "fnc_updateActions", "d4/d62/md_addons_gui_functions_fnc_update_actions.html", null ],
    [ "fnc_updateCategories", "d5/d6d/md_addons_gui_functions_fnc_update_categories.html", null ],
    [ "XEH_postInit", "dd/d38/md_addons_gui__x_e_h_post_init.html", null ],
    [ "XEH_preInit", "d8/d4c/md_addons_gui__x_e_h_pre_init.html", null ],
    [ "XEH_preStart", "dc/df4/md_addons_gui__x_e_h_pre_start.html", null ],
    [ "fnc_actionLowerBy10", "d4/d9d/md_addons_misc_functions_fnc_action_lower_by10.html", null ],
    [ "fnc_addActionRaise", "de/d5e/md_addons_misc_functions_fnc_add_action_raise.html", null ],
    [ "fnc_addIVbag", "d5/d33/md_addons_misc_functions_fnc_add_i_vbag.html", null ],
    [ "fnc_addPassengersActions", "de/dd3/md_addons_misc_functions_fnc_add_passengers_actions.html", null ],
    [ "fnc_attachStretcher", "d7/d01/md_addons_misc_functions_fnc_attach_stretcher.html", null ],
    [ "fnc_conditionIV", "da/d92/md_addons_misc_functions_fnc_condition_i_v.html", null ],
    [ "fnc_conditionIVstand", "d8/ded/md_addons_misc_functions_fnc_condition_i_vstand.html", null ],
    [ "fnc_handleRespawn", "d4/de3/md_addons_misc_functions_fnc_handle_respawn.html", null ],
    [ "fnc_headTourniquet", "d2/d87/md_addons_misc_functions_fnc_head_tourniquet.html", null ],
    [ "fnc_headTourniquetLocal", "d7/d95/md_addons_misc_functions_fnc_head_tourniquet_local.html", null ],
    [ "fnc_heliAddActionDeploy", "db/d3d/md_addons_misc_functions_fnc_heli_add_action_deploy.html", null ],
    [ "fnc_heliStretcherAttach", "d4/d3f/md_addons_misc_functions_fnc_heli_stretcher_attach.html", null ],
    [ "fnc_incompatibilityWarning", "dd/d69/md_addons_misc_functions_fnc_incompatibility_warning.html", null ],
    [ "fnc_init", "da/d22/md_addons_misc_functions_fnc_init.html", null ],
    [ "fnc_removeIVbag", "dc/d2d/md_addons_misc_functions_fnc_remove_i_vbag.html", null ],
    [ "fnc_stretcher", "d2/d2a/md_addons_misc_functions_fnc_stretcher.html", null ],
    [ "fnc_treatmentIV", "d3/d5b/md_addons_misc_functions_fnc_treatment_i_v.html", null ],
    [ "XEH_postInit", "d9/d51/md_addons_misc__x_e_h_post_init.html", null ],
    [ "XEH_preInit", "d7/dec/md_addons_misc__x_e_h_pre_init.html", null ],
    [ "fnc_alphaAction", "d1/d7b/md_addons_pharma_functions_fnc_alpha_action.html", null ],
    [ "fnc_applyIV", "db/d2a/md_addons_pharma_functions_fnc_apply_i_v.html", null ],
    [ "fnc_checkIV", "dd/dae/md_addons_pharma_functions_fnc_check_i_v.html", null ],
    [ "fnc_fentanylPP", "d5/df6/md_addons_pharma_functions_fnc_fentanyl_p_p.html", null ],
    [ "fnc_fluid", "d1/ded/md_addons_pharma_functions_fnc_fluid.html", null ],
    [ "fnc_fluidLocal", "d5/deb/md_addons_pharma_functions_fnc_fluid_local.html", null ],
    [ "fnc_getBloodLoss", "d5/d43/md_addons_pharma_functions_fnc_get_blood_loss.html", null ],
    [ "fnc_getBloodVolumeChange", "d4/d71/md_addons_pharma_functions_fnc_get_blood_volume_change.html", null ],
    [ "fnc_hasStableVitals", "d2/d5b/md_addons_pharma_functions_fnc_has_stable_vitals.html", null ],
    [ "fnc_init", "d5/d40/md_addons_pharma_functions_fnc_init.html", null ],
    [ "fnc_inspectBreath", "d1/dd8/md_addons_pharma_functions_fnc_inspect_breath.html", null ],
    [ "fnc_inspectCatheter", "d4/d23/md_addons_pharma_functions_fnc_inspect_catheter.html", null ],
    [ "fnc_ketaminePP", "d9/d01/md_addons_pharma_functions_fnc_ketamine_p_p.html", null ],
    [ "fnc_pervitinPP", "da/d94/md_addons_pharma_functions_fnc_pervitin_p_p.html", null ],
    [ "fnc_removeItemfromMag", "d5/d6e/md_addons_pharma_functions_fnc_remove_itemfrom_mag.html", null ],
    [ "fnc_removeIV", "d4/d94/md_addons_pharma_functions_fnc_remove_i_v.html", null ],
    [ "fnc_retrieveIV", "d4/d22/md_addons_pharma_functions_fnc_retrieve_i_v.html", null ],
    [ "fnc_salineCheck", "d9/d7b/md_addons_pharma_functions_fnc_saline_check.html", null ],
    [ "fnc_treatmentAdvanced_Amiodarone", "dc/d69/md_addons_pharma_functions_fnc_treatment_advanced__amiodarone.html", null ],
    [ "fnc_treatmentAdvanced_AmiodaroneLocal", "de/d04/md_addons_pharma_functions_fnc_treatment_advanced__amiodarone_local.html", null ],
    [ "fnc_treatmentAdvanced_Atropine", "de/d1d/md_addons_pharma_functions_fnc_treatment_advanced__atropine.html", null ],
    [ "fnc_treatmentAdvanced_AtropineLocal", "d8/d1c/md_addons_pharma_functions_fnc_treatment_advanced__atropine_local.html", null ],
    [ "fnc_treatmentAdvanced_Caffeine", "de/db0/md_addons_pharma_functions_fnc_treatment_advanced__caffeine.html", null ],
    [ "fnc_treatmentAdvanced_CaffeineLocal", "dc/d84/md_addons_pharma_functions_fnc_treatment_advanced__caffeine_local.html", null ],
    [ "fnc_treatmentAdvanced_Carbonate", "d6/d1b/md_addons_pharma_functions_fnc_treatment_advanced__carbonate.html", null ],
    [ "fnc_treatmentAdvanced_CarbonateLocal", "d9/d62/md_addons_pharma_functions_fnc_treatment_advanced__carbonate_local.html", null ],
    [ "fnc_treatmentAdvanced_Dialysis", "d1/d13/md_addons_pharma_functions_fnc_treatment_advanced__dialysis.html", null ],
    [ "fnc_treatmentAdvanced_DialysisLocal", "d6/d0d/md_addons_pharma_functions_fnc_treatment_advanced__dialysis_local.html", null ],
    [ "fnc_treatmentAdvanced_EACA", "db/dee/md_addons_pharma_functions_fnc_treatment_advanced__e_a_c_a.html", null ],
    [ "fnc_treatmentAdvanced_EACALocal", "d3/d18/md_addons_pharma_functions_fnc_treatment_advanced__e_a_c_a_local.html", null ],
    [ "fnc_treatmentAdvanced_Fentanyl", "dd/d6a/md_addons_pharma_functions_fnc_treatment_advanced__fentanyl.html", null ],
    [ "fnc_treatmentAdvanced_Flumazenil", "d2/dcc/md_addons_pharma_functions_fnc_treatment_advanced__flumazenil.html", null ],
    [ "fnc_treatmentAdvanced_FlumazenilLocal", "d9/d0b/md_addons_pharma_functions_fnc_treatment_advanced__flumazenil_local.html", null ],
    [ "fnc_treatmentAdvanced_Flush", "d3/d1f/md_addons_pharma_functions_fnc_treatment_advanced__flush.html", null ],
    [ "fnc_treatmentAdvanced_FlushLocal", "d5/dab/md_addons_pharma_functions_fnc_treatment_advanced__flush_local.html", null ],
    [ "fnc_treatmentAdvanced_Ketamine", "de/d6e/md_addons_pharma_functions_fnc_treatment_advanced__ketamine.html", null ],
    [ "fnc_treatmentAdvanced_Lorazepam", "d5/d0e/md_addons_pharma_functions_fnc_treatment_advanced__lorazepam.html", null ],
    [ "fnc_treatmentAdvanced_LorazepamLocal", "d7/d9f/md_addons_pharma_functions_fnc_treatment_advanced__lorazepam_local.html", null ],
    [ "fnc_treatmentAdvanced_medication", "d5/df9/md_addons_pharma_functions_fnc_treatment_advanced_medication.html", null ],
    [ "fnc_treatmentAdvanced_medicationLocal", "dd/d55/md_addons_pharma_functions_fnc_treatment_advanced_medication_local.html", null ],
    [ "fnc_treatmentAdvanced_Naloxone", "d9/dc3/md_addons_pharma_functions_fnc_treatment_advanced__naloxone.html", null ],
    [ "fnc_treatmentAdvanced_NaloxoneLocal", "d7/d49/md_addons_pharma_functions_fnc_treatment_advanced__naloxone_local.html", null ],
    [ "fnc_treatmentAdvanced_Painkillers", "d7/d5a/md_addons_pharma_functions_fnc_treatment_advanced__painkillers.html", null ],
    [ "fnc_treatmentAdvanced_Pervitin", "df/d46/md_addons_pharma_functions_fnc_treatment_advanced__pervitin.html", null ],
    [ "fnc_treatmentAdvanced_PervitinLocal", "de/d82/md_addons_pharma_functions_fnc_treatment_advanced__pervitin_local.html", null ],
    [ "fnc_treatmentAdvanced_Reorientation", "de/d42/md_addons_pharma_functions_fnc_treatment_advanced__reorientation.html", null ],
    [ "fnc_treatmentAdvanced_ReorientationLocal", "db/dde/md_addons_pharma_functions_fnc_treatment_advanced__reorientation_local.html", null ],
    [ "fnc_treatmentAdvanced_TXA", "dc/d41/md_addons_pharma_functions_fnc_treatment_advanced__t_x_a.html", null ],
    [ "fnc_treatmentAdvanced_TXALocal", "d5/d48/md_addons_pharma_functions_fnc_treatment_advanced__t_x_a_local.html", null ],
    [ "fnc_vehicleCheckDialysis", "d8/d95/md_addons_pharma_functions_fnc_vehicle_check_dialysis.html", null ],
    [ "XEH_postInit", "d7/de4/md_addons_pharma__x_e_h_post_init.html", null ],
    [ "XEH_preInit", "d1/df2/md_addons_pharma__x_e_h_pre_init.html", null ],
    [ "fnc_closedReduction", "d8/dfe/md_addons_surgery_functions_fnc_closed_reduction.html", null ],
    [ "fnc_closedReductionLocal", "db/d00/md_addons_surgery_functions_fnc_closed_reduction_local.html", null ],
    [ "fnc_debridement", "d3/d89/md_addons_surgery_functions_fnc_debridement.html", null ],
    [ "fnc_debridementCheck", "d8/dca/md_addons_surgery_functions_fnc_debridement_check.html", null ],
    [ "fnc_debridementLocal", "d1/d05/md_addons_surgery_functions_fnc_debridement_local.html", null ],
    [ "fnc_fractureCheck", "d0/de8/md_addons_surgery_functions_fnc_fracture_check.html", null ],
    [ "fnc_fractureSelect", "d0/dad/md_addons_surgery_functions_fnc_fracture_select.html", null ],
    [ "fnc_fractureSelectLocal", "d9/d6f/md_addons_surgery_functions_fnc_fracture_select_local.html", null ],
    [ "fnc_incision", "df/ded/md_addons_surgery_functions_fnc_incision.html", null ],
    [ "fnc_incisionLocal", "d1/d8d/md_addons_surgery_functions_fnc_incision_local.html", null ],
    [ "fnc_init", "d1/df8/md_addons_surgery_functions_fnc_init.html", null ],
    [ "fnc_npwtTreatment", "de/d7f/md_addons_surgery_functions_fnc_npwt_treatment.html", null ],
    [ "fnc_npwtTreatmentLocal", "db/d25/md_addons_surgery_functions_fnc_npwt_treatment_local.html", null ],
    [ "fnc_openReduction", "df/d72/md_addons_surgery_functions_fnc_open_reduction.html", null ],
    [ "fnc_openReductionCheck", "d0/d93/md_addons_surgery_functions_fnc_open_reduction_check.html", null ],
    [ "fnc_openReductionLocal", "d0/d3c/md_addons_surgery_functions_fnc_open_reduction_local.html", null ],
    [ "fnc_openReductionProgress", "da/d6d/md_addons_surgery_functions_fnc_open_reduction_progress.html", null ],
    [ "fnc_openReductionProgressLocal", "dc/d4c/md_addons_surgery_functions_fnc_open_reduction_progress_local.html", null ],
    [ "XEH_postInit", "d3/dd5/md_addons_surgery__x_e_h_post_init.html", null ],
    [ "XEH_preInit", "d7/db5/md_addons_surgery__x_e_h_pre_init.html", null ],
    [ "fnc_emptyFunction", "d0/d6f/md_addons_zeus_functions_fnc_empty_function.html", null ],
    [ "fnc_menuPFH", "d4/d76/md_addons_zeus_functions_fnc_menu_p_f_h.html", null ],
    [ "fnc_openMedicalMenu", "d0/d75/md_addons_zeus_functions_fnc_open_medical_menu.html", null ],
    [ "fnc_showMessage", "de/ddb/md_addons_zeus_functions_fnc_show_message.html", null ],
    [ "fnc_ui_changeAsystole", "d7/da3/md_addons_zeus_functions_fnc_ui_change_asystole.html", null ],
    [ "fnc_ui_changeBloodType", "d9/dab/md_addons_zeus_functions_fnc_ui_change_blood_type.html", null ],
    [ "fnc_ui_manageAirway", "dc/d1f/md_addons_zeus_functions_fnc_ui_manage_airway.html", null ],
    [ "fnc_zeusAttributes", "d6/d38/md_addons_zeus_functions_fnc_zeus_attributes.html", null ],
    [ "XEH_postInit", "d1/dac/md_addons_zeus__x_e_h_post_init.html", null ],
    [ "XEH_preInit", "d1/d1a/md_addons_zeus__x_e_h_pre_init.html", null ],
    [ "Data Structures", "annotated.html", [
      [ "Data Structures", "annotated.html", "annotated_dup" ],
      [ "Data Structure Index", "classes.html", null ],
      [ "Class Hierarchy", "hierarchy.html", "hierarchy" ]
    ] ],
    [ "Files", "files.html", [
      [ "File List", "files.html", "files_dup" ],
      [ "Globals", "globals.html", [
        [ "All", "globals.html", "globals_dup" ],
        [ "Functions", "globals_func.html", "globals_func" ],
        [ "Macros", "globals_defs.html", "globals_defs" ]
      ] ]
    ] ]
  ] ]
];

var NAVTREEINDEX =
[
"annotated.html",
"d3/d4a/class_extended___post_init___event_handlers.html",
"d7/d29/misc_2functions_2script__component_8hpp_af150aa072c06aaec8badc030f9b36ff3.html#af150aa072c06aaec8badc030f9b36ff3",
"da/df3/script__macros_8hpp_a7b90a69463bbcf5aedb320f35d31b3af.html#a7b90a69463bbcf5aedb320f35d31b3af",
"dd/de2/breathing_2_x_e_h___p_r_e_p_8hpp_ad53c9cc34c4f5ed05d67202944ee09f2.html#ad53c9cc34c4f5ed05d67202944ee09f2",
"globals_z.html"
];

var SYNCONMSG = 'click to disable panel synchronisation';
var SYNCOFFMSG = 'click to enable panel synchronisation';