/*
 @licstart  The following is the entire license notice for the JavaScript code in this file.

 The MIT License (MIT)

 Copyright (C) 1997-2020 by Dimitri van Heesch

 Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 and associated documentation files (the "Software"), to deal in the Software without restriction,
 including without limitation the rights to use, copy, modify, merge, publish, distribute,
 sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all copies or
 substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
 BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

 @licend  The above is the entire license notice for the JavaScript code in this file
*/
var NAVTREE =
[
  [ "KAT - Advanced Medical", "index.html", [
    [ "fnc_checkAirway", "md_addons_airway_functions_fnc_check_airway.html", null ],
    [ "fnc_checkRecovery", "md_addons_airway_functions_fnc_check_recovery.html", null ],
    [ "fnc_displayPatientInformation", "md_addons_airway_functions_fnc_display_patient_information.html", null ],
    [ "fnc_handleAirway", "md_addons_airway_functions_fnc_handle_airway.html", null ],
    [ "fnc_handlePuking", "md_addons_airway_functions_fnc_handle_puking.html", null ],
    [ "fnc_init", "md_addons_airway_functions_fnc_init.html", null ],
    [ "fnc_setUnconscious", "md_addons_airway_functions_fnc_set_unconscious.html", null ],
    [ "fnc_treatmentAdvanced_Accuvac", "md_addons_airway_functions_fnc_treatment_advanced__accuvac.html", null ],
    [ "fnc_treatmentAdvanced_AccuvacLocal", "md_addons_airway_functions_fnc_treatment_advanced__accuvac_local.html", null ],
    [ "fnc_treatmentAdvanced_airway", "md_addons_airway_functions_fnc_treatment_advanced_airway.html", null ],
    [ "fnc_treatmentAdvanced_airwayLocal", "md_addons_airway_functions_fnc_treatment_advanced_airway_local.html", null ],
    [ "fnc_treatmentAdvanced_CancelRecoveryPosition", "md_addons_airway_functions_fnc_treatment_advanced__cancel_recovery_position.html", null ],
    [ "fnc_treatmentAdvanced_CancelRecoveryPositionLocal", "md_addons_airway_functions_fnc_treatment_advanced__cancel_recovery_position_local.html", null ],
    [ "fnc_treatmentAdvanced_overstretchHead", "md_addons_airway_functions_fnc_treatment_advanced_overstretch_head.html", null ],
    [ "fnc_treatmentAdvanced_RecoveryPosition", "md_addons_airway_functions_fnc_treatment_advanced__recovery_position.html", null ],
    [ "fnc_treatmentAdvanced_RecoveryPositionLocal", "md_addons_airway_functions_fnc_treatment_advanced__recovery_position_local.html", null ],
    [ "fnc_treatmentAdvanced_RemoveAirwayItem", "md_addons_airway_functions_fnc_treatment_advanced__remove_airway_item.html", null ],
    [ "fnc_treatmentAdvanced_RemoveAirwayItemLocal", "md_addons_airway_functions_fnc_treatment_advanced__remove_airway_item_local.html", null ],
    [ "fnc_treatmentAdvanced_turnaroundHead", "md_addons_airway_functions_fnc_treatment_advanced_turnaround_head.html", null ],
    [ "fnc_updateInjuryList", "md_addons_airway_functions_fnc_update_injury_list.html", null ],
    [ "fnc_updateLogList", "md_addons_airway_functions_fnc_update_log_list.html", null ],
    [ "XEH_postInit", "md_addons_airway__x_e_h_post_init.html", null ],
    [ "XEH_preInit", "md_addons_airway__x_e_h_pre_init.html", null ],
    [ "fnc_canUseBVM", "md_addons_breathing_functions_fnc_can_use_b_v_m.html", null ],
    [ "fnc_checkPulseOximeter", "md_addons_breathing_functions_fnc_check_pulse_oximeter.html", null ],
    [ "fnc_fullHealLocal", "md_addons_breathing_functions_fnc_full_heal_local.html", null ],
    [ "fnc_handleBreathing", "md_addons_breathing_functions_fnc_handle_breathing.html", null ],
    [ "fnc_handlePulmoHit", "md_addons_breathing_functions_fnc_handle_pulmo_hit.html", null ],
    [ "fnc_hasBVM", "md_addons_breathing_functions_fnc_has_b_v_m.html", null ],
    [ "fnc_hasOxygenTank", "md_addons_breathing_functions_fnc_has_oxygen_tank.html", null ],
    [ "fnc_init", "md_addons_breathing_functions_fnc_init.html", null ],
    [ "fnc_listenLungs", "md_addons_breathing_functions_fnc_listen_lungs.html", null ],
    [ "fnc_lowSpO2pp", "md_addons_breathing_functions_fnc_low_sp_o2pp.html", null ],
    [ "fnc_refillOxygenTank", "md_addons_breathing_functions_fnc_refill_oxygen_tank.html", null ],
    [ "fnc_treatmentAdvanced_chestSeal", "md_addons_breathing_functions_fnc_treatment_advanced_chest_seal.html", null ],
    [ "fnc_treatmentAdvanced_chestSealLocal", "md_addons_breathing_functions_fnc_treatment_advanced_chest_seal_local.html", null ],
    [ "fnc_treatmentAdvanced_Cyanosis", "md_addons_breathing_functions_fnc_treatment_advanced__cyanosis.html", null ],
    [ "fnc_treatmentAdvanced_CyanosisLocal", "md_addons_breathing_functions_fnc_treatment_advanced__cyanosis_local.html", null ],
    [ "fnc_treatmentAdvanced_hemopneumothorax", "md_addons_breathing_functions_fnc_treatment_advanced_hemopneumothorax.html", null ],
    [ "fnc_treatmentAdvanced_hemopneumothoraxLocal", "md_addons_breathing_functions_fnc_treatment_advanced_hemopneumothorax_local.html", null ],
    [ "fnc_treatmentAdvanced_pulseoximeter", "md_addons_breathing_functions_fnc_treatment_advanced_pulseoximeter.html", null ],
    [ "fnc_treatmentAdvanced_pulseoximeterLocal", "md_addons_breathing_functions_fnc_treatment_advanced_pulseoximeter_local.html", null ],
    [ "fnc_treatmentAdvanced_removePulseoximeter", "md_addons_breathing_functions_fnc_treatment_advanced_remove_pulseoximeter.html", null ],
    [ "fnc_treatmentAdvanced_tensionpneumothorax", "md_addons_breathing_functions_fnc_treatment_advanced_tensionpneumothorax.html", null ],
    [ "fnc_treatmentAdvanced_tensionpneumothoraxLocal", "md_addons_breathing_functions_fnc_treatment_advanced_tensionpneumothorax_local.html", null ],
    [ "fnc_useBVM", "md_addons_breathing_functions_fnc_use_b_v_m.html", null ],
    [ "XEH_postInit", "md_addons_breathing__x_e_h_post_init.html", null ],
    [ "XEH_preInit", "md_addons_breathing__x_e_h_pre_init.html", null ],
    [ "fnc_addLoadAction", "md_addons_chemical_functions_fnc_add_load_action.html", null ],
    [ "fnc_afterWait", "md_addons_chemical_functions_fnc_after_wait.html", null ],
    [ "fnc_AttributeRadius", "md_addons_chemical_functions_fnc__attribute_radius.html", null ],
    [ "fnc_breathing", "md_addons_chemical_functions_fnc_breathing.html", null ],
    [ "fnc_canPutGasMask", "md_addons_chemical_functions_fnc_can_put_gas_mask.html", null ],
    [ "fnc_canReplaceFilter", "md_addons_chemical_functions_fnc_can_replace_filter.html", null ],
    [ "fnc_CASCreateGas", "md_addons_chemical_functions_fnc__c_a_s_create_gas.html", null ],
    [ "fnc_changeGasMaskFilter", "md_addons_chemical_functions_fnc_change_gas_mask_filter.html", null ],
    [ "fnc_checkGasMaskDur", "md_addons_chemical_functions_fnc_check_gas_mask_dur.html", null ],
    [ "fnc_chemDetector", "md_addons_chemical_functions_fnc_chem_detector.html", null ],
    [ "fnc_coughing", "md_addons_chemical_functions_fnc_coughing.html", null ],
    [ "fnc_createSealAction", "md_addons_chemical_functions_fnc_create_seal_action.html", null ],
    [ "fnc_createZone", "md_addons_chemical_functions_fnc_create_zone.html", null ],
    [ "fnc_csGrenadeThrownFuze", "md_addons_chemical_functions_fnc_cs_grenade_thrown_fuze.html", null ],
    [ "fnc_displayGasMaskDur", "md_addons_chemical_functions_fnc_display_gas_mask_dur.html", null ],
    [ "fnc_gasAI", "md_addons_chemical_functions_fnc_gas_a_i.html", null ],
    [ "fnc_gasCheck", "md_addons_chemical_functions_fnc_gas_check.html", null ],
    [ "fnc_gasCheckLocal", "md_addons_chemical_functions_fnc_gas_check_local.html", null ],
    [ "fnc_gasmodule", "md_addons_chemical_functions_fnc_gasmodule.html", null ],
    [ "fnc_GasTripEffect", "md_addons_chemical_functions_fnc__gas_trip_effect.html", null ],
    [ "fnc_getChemDetectorState", "md_addons_chemical_functions_fnc_get_chem_detector_state.html", null ],
    [ "fnc_getList", "md_addons_chemical_functions_fnc_get_list.html", null ],
    [ "fnc_giveUnitGasMask", "md_addons_chemical_functions_fnc_give_unit_gas_mask.html", null ],
    [ "fnc_handleCSGas", "md_addons_chemical_functions_fnc_handle_c_s_gas.html", null ],
    [ "fnc_handleFired", "md_addons_chemical_functions_fnc_handle_fired.html", null ],
    [ "fnc_handleGasMaskDur", "md_addons_chemical_functions_fnc_handle_gas_mask_dur.html", null ],
    [ "fnc_handleSlotItemChanged", "md_addons_chemical_functions_fnc_handle_slot_item_changed.html", null ],
    [ "fnc_hasGasmask", "md_addons_chemical_functions_fnc_has_gasmask.html", null ],
    [ "fnc_hasGasMaskON", "md_addons_chemical_functions_fnc_has_gas_mask_o_n.html", null ],
    [ "fnc_init", "md_addons_chemical_functions_fnc_init.html", null ],
    [ "fnc_initModule", "md_addons_chemical_functions_fnc_init_module.html", null ],
    [ "fnc_spawnGasSmoke", "md_addons_chemical_functions_fnc_spawn_gas_smoke.html", null ],
    [ "fnc_spawnSmoke", "md_addons_chemical_functions_fnc_spawn_smoke.html", null ],
    [ "fnc_throwGrenade", "md_addons_chemical_functions_fnc_throw_grenade.html", null ],
    [ "fnc_ui_gasModule", "md_addons_chemical_functions_fnc_ui_gas_module.html", null ],
    [ "fnc_updateBodyImage", "md_addons_chemical_functions_fnc_update_body_image.html", null ],
    [ "XEH_postInit", "md_addons_chemical__x_e_h_post_init.html", null ],
    [ "XEH_preInit", "md_addons_chemical__x_e_h_pre_init.html", null ],
    [ "fnc_AED_sound", "md_addons_circulation_functions_fnc__a_e_d_sound.html", null ],
    [ "fnc_AEDanalyze", "md_addons_circulation_functions_fnc__a_e_danalyze.html", null ],
    [ "fnc_AEDFailure", "md_addons_circulation_functions_fnc__a_e_d_failure.html", null ],
    [ "fnc_AEDProgress", "md_addons_circulation_functions_fnc__a_e_d_progress.html", null ],
    [ "fnc_AEDStart", "md_addons_circulation_functions_fnc__a_e_d_start.html", null ],
    [ "fnc_AEDStationCondition", "md_addons_circulation_functions_fnc__a_e_d_station_condition.html", null ],
    [ "fnc_AEDSuccess", "md_addons_circulation_functions_fnc__a_e_d_success.html", null ],
    [ "fnc_AEDXCondition", "md_addons_circulation_functions_fnc__a_e_d_x_condition.html", null ],
    [ "fnc_attachAEDX", "md_addons_circulation_functions_fnc_attach_a_e_d_x.html", null ],
    [ "fnc_attachAEDXVehicle", "md_addons_circulation_functions_fnc_attach_a_e_d_x_vehicle.html", null ],
    [ "fnc_bloodType", "md_addons_circulation_functions_fnc_blood_type.html", null ],
    [ "fnc_canCheckDogtag", "md_addons_circulation_functions_fnc_can_check_dogtag.html", null ],
    [ "fnc_canDraw", "md_addons_circulation_functions_fnc_can_draw.html", null ],
    [ "fnc_compatible", "md_addons_circulation_functions_fnc_compatible.html", null ],
    [ "fnc_cprLocal", "md_addons_circulation_functions_fnc_cpr_local.html", null ],
    [ "fnc_cprSuccess", "md_addons_circulation_functions_fnc_cpr_success.html", null ],
    [ "fnc_drawBlood", "md_addons_circulation_functions_fnc_draw_blood.html", null ],
    [ "fnc_generateBloodType", "md_addons_circulation_functions_fnc_generate_blood_type.html", null ],
    [ "fnc_getDogtagData", "md_addons_circulation_functions_fnc_get_dogtag_data.html", null ],
    [ "fnc_groupID", "md_addons_circulation_functions_fnc_group_i_d.html", null ],
    [ "fnc_handleTreatment", "md_addons_circulation_functions_fnc_handle_treatment.html", null ],
    [ "fnc_init", "md_addons_circulation_functions_fnc_init.html", null ],
    [ "fnc_onCloseDialog", "md_addons_circulation_functions_fnc_on_close_dialog.html", null ],
    [ "fnc_placeAED", "md_addons_circulation_functions_fnc_place_a_e_d.html", null ],
    [ "fnc_removeLog", "md_addons_circulation_functions_fnc_remove_log.html", null ],
    [ "fnc_returnAED_X", "md_addons_circulation_functions_fnc_return_a_e_d__x.html", null ],
    [ "fnc_treatment", "md_addons_circulation_functions_fnc_treatment.html", null ],
    [ "fnc_treatmentAdvanced_IV", "md_addons_circulation_functions_fnc_treatment_advanced__i_v.html", null ],
    [ "fnc_updateInternalBleeding", "md_addons_circulation_functions_fnc_update_internal_bleeding.html", null ],
    [ "fnc_vehicleCheck", "md_addons_circulation_functions_fnc_vehicle_check.html", null ],
    [ "fnc_wrongBloodTreatment", "md_addons_circulation_functions_fnc_wrong_blood_treatment.html", null ],
    [ "XEH_postInit", "md_addons_circulation__x_e_h_post_init.html", null ],
    [ "XEH_preInit", "md_addons_circulation__x_e_h_pre_init.html", null ],
    [ "fnc_onMenuOpen", "md_addons_gui_functions_fnc_on_menu_open.html", null ],
    [ "fnc_updateActions", "md_addons_gui_functions_fnc_update_actions.html", null ],
    [ "fnc_updateCategories", "md_addons_gui_functions_fnc_update_categories.html", null ],
    [ "XEH_postInit", "md_addons_gui__x_e_h_post_init.html", null ],
    [ "XEH_preInit", "md_addons_gui__x_e_h_pre_init.html", null ],
    [ "XEH_preStart", "md_addons_gui__x_e_h_pre_start.html", null ],
    [ "fnc_actionLowerBy10", "md_addons_misc_functions_fnc_action_lower_by10.html", null ],
    [ "fnc_addActionRaise", "md_addons_misc_functions_fnc_add_action_raise.html", null ],
    [ "fnc_addIVbag", "md_addons_misc_functions_fnc_add_i_vbag.html", null ],
    [ "fnc_addPassengersActions", "md_addons_misc_functions_fnc_add_passengers_actions.html", null ],
    [ "fnc_attachStretcher", "md_addons_misc_functions_fnc_attach_stretcher.html", null ],
    [ "fnc_conditionIV", "md_addons_misc_functions_fnc_condition_i_v.html", null ],
    [ "fnc_conditionIVstand", "md_addons_misc_functions_fnc_condition_i_vstand.html", null ],
    [ "fnc_handleRespawn", "md_addons_misc_functions_fnc_handle_respawn.html", null ],
    [ "fnc_headTourniquet", "md_addons_misc_functions_fnc_head_tourniquet.html", null ],
    [ "fnc_headTourniquetLocal", "md_addons_misc_functions_fnc_head_tourniquet_local.html", null ],
    [ "fnc_heliAddActionDeploy", "md_addons_misc_functions_fnc_heli_add_action_deploy.html", null ],
    [ "fnc_heliStretcherAttach", "md_addons_misc_functions_fnc_heli_stretcher_attach.html", null ],
    [ "fnc_incompatibilityWarning", "md_addons_misc_functions_fnc_incompatibility_warning.html", null ],
    [ "fnc_init", "md_addons_misc_functions_fnc_init.html", null ],
    [ "fnc_removeIVbag", "md_addons_misc_functions_fnc_remove_i_vbag.html", null ],
    [ "fnc_stretcher", "md_addons_misc_functions_fnc_stretcher.html", null ],
    [ "fnc_treatmentIV", "md_addons_misc_functions_fnc_treatment_i_v.html", null ],
    [ "XEH_postInit", "md_addons_misc__x_e_h_post_init.html", null ],
    [ "XEH_preInit", "md_addons_misc__x_e_h_pre_init.html", null ],
    [ "fnc_alphaAction", "md_addons_pharma_functions_fnc_alpha_action.html", null ],
    [ "fnc_applyIV", "md_addons_pharma_functions_fnc_apply_i_v.html", null ],
    [ "fnc_checkIV", "md_addons_pharma_functions_fnc_check_i_v.html", null ],
    [ "fnc_fentanylPP", "md_addons_pharma_functions_fnc_fentanyl_p_p.html", null ],
    [ "fnc_fluid", "md_addons_pharma_functions_fnc_fluid.html", null ],
    [ "fnc_fluidLocal", "md_addons_pharma_functions_fnc_fluid_local.html", null ],
    [ "fnc_getBloodLoss", "md_addons_pharma_functions_fnc_get_blood_loss.html", null ],
    [ "fnc_getBloodVolumeChange", "md_addons_pharma_functions_fnc_get_blood_volume_change.html", null ],
    [ "fnc_hasStableVitals", "md_addons_pharma_functions_fnc_has_stable_vitals.html", null ],
    [ "fnc_init", "md_addons_pharma_functions_fnc_init.html", null ],
    [ "fnc_inspectBreath", "md_addons_pharma_functions_fnc_inspect_breath.html", null ],
    [ "fnc_inspectCatheter", "md_addons_pharma_functions_fnc_inspect_catheter.html", null ],
    [ "fnc_ketaminePP", "md_addons_pharma_functions_fnc_ketamine_p_p.html", null ],
    [ "fnc_pervitinPP", "md_addons_pharma_functions_fnc_pervitin_p_p.html", null ],
    [ "fnc_removeItemfromMag", "md_addons_pharma_functions_fnc_remove_itemfrom_mag.html", null ],
    [ "fnc_removeIV", "md_addons_pharma_functions_fnc_remove_i_v.html", null ],
    [ "fnc_retrieveIV", "md_addons_pharma_functions_fnc_retrieve_i_v.html", null ],
    [ "fnc_salineCheck", "md_addons_pharma_functions_fnc_saline_check.html", null ],
    [ "fnc_treatmentAdvanced_Amiodarone", "md_addons_pharma_functions_fnc_treatment_advanced__amiodarone.html", null ],
    [ "fnc_treatmentAdvanced_AmiodaroneLocal", "md_addons_pharma_functions_fnc_treatment_advanced__amiodarone_local.html", null ],
    [ "fnc_treatmentAdvanced_Atropine", "md_addons_pharma_functions_fnc_treatment_advanced__atropine.html", null ],
    [ "fnc_treatmentAdvanced_AtropineLocal", "md_addons_pharma_functions_fnc_treatment_advanced__atropine_local.html", null ],
    [ "fnc_treatmentAdvanced_Caffeine", "md_addons_pharma_functions_fnc_treatment_advanced__caffeine.html", null ],
    [ "fnc_treatmentAdvanced_CaffeineLocal", "md_addons_pharma_functions_fnc_treatment_advanced__caffeine_local.html", null ],
    [ "fnc_treatmentAdvanced_Carbonate", "md_addons_pharma_functions_fnc_treatment_advanced__carbonate.html", null ],
    [ "fnc_treatmentAdvanced_CarbonateLocal", "md_addons_pharma_functions_fnc_treatment_advanced__carbonate_local.html", null ],
    [ "fnc_treatmentAdvanced_Dialysis", "md_addons_pharma_functions_fnc_treatment_advanced__dialysis.html", null ],
    [ "fnc_treatmentAdvanced_DialysisLocal", "md_addons_pharma_functions_fnc_treatment_advanced__dialysis_local.html", null ],
    [ "fnc_treatmentAdvanced_EACA", "md_addons_pharma_functions_fnc_treatment_advanced__e_a_c_a.html", null ],
    [ "fnc_treatmentAdvanced_EACALocal", "md_addons_pharma_functions_fnc_treatment_advanced__e_a_c_a_local.html", null ],
    [ "fnc_treatmentAdvanced_Fentanyl", "md_addons_pharma_functions_fnc_treatment_advanced__fentanyl.html", null ],
    [ "fnc_treatmentAdvanced_Flumazenil", "md_addons_pharma_functions_fnc_treatment_advanced__flumazenil.html", null ],
    [ "fnc_treatmentAdvanced_FlumazenilLocal", "md_addons_pharma_functions_fnc_treatment_advanced__flumazenil_local.html", null ],
    [ "fnc_treatmentAdvanced_Flush", "md_addons_pharma_functions_fnc_treatment_advanced__flush.html", null ],
    [ "fnc_treatmentAdvanced_FlushLocal", "md_addons_pharma_functions_fnc_treatment_advanced__flush_local.html", null ],
    [ "fnc_treatmentAdvanced_Ketamine", "md_addons_pharma_functions_fnc_treatment_advanced__ketamine.html", null ],
    [ "fnc_treatmentAdvanced_Lorazepam", "md_addons_pharma_functions_fnc_treatment_advanced__lorazepam.html", null ],
    [ "fnc_treatmentAdvanced_LorazepamLocal", "md_addons_pharma_functions_fnc_treatment_advanced__lorazepam_local.html", null ],
    [ "fnc_treatmentAdvanced_medication", "md_addons_pharma_functions_fnc_treatment_advanced_medication.html", null ],
    [ "fnc_treatmentAdvanced_medicationLocal", "md_addons_pharma_functions_fnc_treatment_advanced_medication_local.html", null ],
    [ "fnc_treatmentAdvanced_Naloxone", "md_addons_pharma_functions_fnc_treatment_advanced__naloxone.html", null ],
    [ "fnc_treatmentAdvanced_NaloxoneLocal", "md_addons_pharma_functions_fnc_treatment_advanced__naloxone_local.html", null ],
    [ "fnc_treatmentAdvanced_Painkillers", "md_addons_pharma_functions_fnc_treatment_advanced__painkillers.html", null ],
    [ "fnc_treatmentAdvanced_Pervitin", "md_addons_pharma_functions_fnc_treatment_advanced__pervitin.html", null ],
    [ "fnc_treatmentAdvanced_PervitinLocal", "md_addons_pharma_functions_fnc_treatment_advanced__pervitin_local.html", null ],
    [ "fnc_treatmentAdvanced_Reorientation", "md_addons_pharma_functions_fnc_treatment_advanced__reorientation.html", null ],
    [ "fnc_treatmentAdvanced_ReorientationLocal", "md_addons_pharma_functions_fnc_treatment_advanced__reorientation_local.html", null ],
    [ "fnc_treatmentAdvanced_TXA", "md_addons_pharma_functions_fnc_treatment_advanced__t_x_a.html", null ],
    [ "fnc_treatmentAdvanced_TXALocal", "md_addons_pharma_functions_fnc_treatment_advanced__t_x_a_local.html", null ],
    [ "fnc_vehicleCheckDialysis", "md_addons_pharma_functions_fnc_vehicle_check_dialysis.html", null ],
    [ "XEH_postInit", "md_addons_pharma__x_e_h_post_init.html", null ],
    [ "XEH_preInit", "md_addons_pharma__x_e_h_pre_init.html", null ],
    [ "fnc_closedReduction", "md_addons_surgery_functions_fnc_closed_reduction.html", null ],
    [ "fnc_closedReductionLocal", "md_addons_surgery_functions_fnc_closed_reduction_local.html", null ],
    [ "fnc_debridement", "md_addons_surgery_functions_fnc_debridement.html", null ],
    [ "fnc_debridementCheck", "md_addons_surgery_functions_fnc_debridement_check.html", null ],
    [ "fnc_debridementLocal", "md_addons_surgery_functions_fnc_debridement_local.html", null ],
    [ "fnc_fractureCheck", "md_addons_surgery_functions_fnc_fracture_check.html", null ],
    [ "fnc_fractureSelect", "md_addons_surgery_functions_fnc_fracture_select.html", null ],
    [ "fnc_fractureSelectLocal", "md_addons_surgery_functions_fnc_fracture_select_local.html", null ],
    [ "fnc_incision", "md_addons_surgery_functions_fnc_incision.html", null ],
    [ "fnc_incisionLocal", "md_addons_surgery_functions_fnc_incision_local.html", null ],
    [ "fnc_init", "md_addons_surgery_functions_fnc_init.html", null ],
    [ "fnc_npwtTreatment", "md_addons_surgery_functions_fnc_npwt_treatment.html", null ],
    [ "fnc_npwtTreatmentLocal", "md_addons_surgery_functions_fnc_npwt_treatment_local.html", null ],
    [ "fnc_openReduction", "md_addons_surgery_functions_fnc_open_reduction.html", null ],
    [ "fnc_openReductionCheck", "md_addons_surgery_functions_fnc_open_reduction_check.html", null ],
    [ "fnc_openReductionLocal", "md_addons_surgery_functions_fnc_open_reduction_local.html", null ],
    [ "fnc_openReductionProgress", "md_addons_surgery_functions_fnc_open_reduction_progress.html", null ],
    [ "fnc_openReductionProgressLocal", "md_addons_surgery_functions_fnc_open_reduction_progress_local.html", null ],
    [ "XEH_postInit", "md_addons_surgery__x_e_h_post_init.html", null ],
    [ "XEH_preInit", "md_addons_surgery__x_e_h_pre_init.html", null ],
    [ "fnc_emptyFunction", "md_addons_zeus_functions_fnc_empty_function.html", null ],
    [ "fnc_menuPFH", "md_addons_zeus_functions_fnc_menu_p_f_h.html", null ],
    [ "fnc_openMedicalMenu", "md_addons_zeus_functions_fnc_open_medical_menu.html", null ],
    [ "fnc_showMessage", "md_addons_zeus_functions_fnc_show_message.html", null ],
    [ "fnc_ui_changeAsystole", "md_addons_zeus_functions_fnc_ui_change_asystole.html", null ],
    [ "fnc_ui_changeBloodType", "md_addons_zeus_functions_fnc_ui_change_blood_type.html", null ],
    [ "fnc_ui_manageAirway", "md_addons_zeus_functions_fnc_ui_manage_airway.html", null ],
    [ "fnc_zeusAttributes", "md_addons_zeus_functions_fnc_zeus_attributes.html", null ],
    [ "XEH_postInit", "md_addons_zeus__x_e_h_post_init.html", null ],
    [ "XEH_preInit", "md_addons_zeus__x_e_h_pre_init.html", null ],
    [ "Data Structures", "annotated.html", [
      [ "Data Structures", "annotated.html", "annotated_dup" ],
      [ "Data Structure Index", "classes.html", null ],
      [ "Class Hierarchy", "hierarchy.html", "hierarchy" ]
    ] ],
    [ "Files", "files.html", [
      [ "File List", "files.html", "files_dup" ],
      [ "Globals", "globals.html", [
        [ "All", "globals.html", "globals_dup" ],
        [ "Functions", "globals_func.html", "globals_func" ],
        [ "Macros", "globals_defs.html", "globals_defs" ]
      ] ]
    ] ]
  ] ]
];

var NAVTREEINDEX =
[
"_blood___medical_8hpp.html",
"chemical_2script__component_8hpp.html#a0faf7ee13f600b59de63c41026651b62",
"dir_53f7f534fb74ff1ab03332b3b0971b5d.html",
"md_addons_circulation_functions_fnc_group_i_d.html",
"pharma_2functions_2script__component_8hpp.html#a0a733042fb6d7c9fc2857113ca36931c",
"zeus_2script__component_8hpp.html#aaf31ae497e432844e334de3cb26578cb"
];

var SYNCONMSG = 'click to disable panel synchronisation';
var SYNCOFFMSG = 'click to enable panel synchronisation';